export const T0=[
 {id:1,g:"BUGs",t:"1.2 - Transacao Aiqfome - Split zerado para seller",c:"BUG-B63B",v:"",s:"Bloqueado",r:"Lourene",mr:"",a:"10/11 - Aberto thread com o time do Uncle\n04/11 - Termino da analise\n03/11 - Inicio da analise"},
 {id:2,g:"BUGs",t:"1.19 - [Atualizacao Pedido] Erro de transicao no Velocity",c:"BUG-1090",v:"",s:"Nao Iniciado",r:"",mr:"",a:""},
 {id:3,g:"BUGs",t:"1.20 - No account ausente no payload Uncle",c:"BUG-B274",v:"",s:"Nao Iniciado",r:"",mr:"",a:""},
 {id:4,g:"Demais Atividades",t:"2.2 - [Risk Center] Analise DPAN",c:"RSCH-3D04",v:"",s:"Nao Iniciado",r:"",mr:"",a:""},
 {id:5,g:"Demais Atividades",t:"2.3 - [Retentativa] Normalizar registros order_retry",c:"BUG-3100",v:"",s:"Nao Iniciado",r:"",mr:"",a:""},
 {id:6,g:"Demais Atividades",t:"2.6 - [KONDUTO] Permitir o tipo boleto",c:"IMP-55CB",v:"",s:"Paralisado",r:"Lourene",mr:"https://gitlab.luizalabs.com/luizalabs/fintech/sesamo/-/merge_requests/2419",a:"06/01 - Verificar voucher x antifraude\n22/08 - Liberado em STG\n17/07 - Inicio do desenvolvimento"},
 {id:7,g:"Demais Atividades",t:"2.7 - Ajuste endpoint criacao canal",c:"IMP-73B6",v:"",s:"Paralisado",r:"Lourene",mr:"https://gitlab.luizalabs.com/luizalabs/fintech/sesamo/-/merge_requests/2789",a:"21/01 - MR validado\n15/12 - Inicio do desenvolvimento"},
 {id:8,g:"Demais Atividades",t:"2.14 - [Multiplas Formas] Inclusao dos Logs",c:"IMP-DE2D",v:"",s:"Nao Iniciado",r:"",mr:"",a:""},
 {id:9,g:"Demais Atividades",t:"2.19 - [Worker cancel_transaction] Campos channel e split nulos",c:"IMP-4E1A",v:"",s:"Nao Iniciado",r:"",mr:"",a:""},
 {id:10,g:"Demais Atividades",t:"2.24 - [PIX] Retentativa de pagamento QR CODE",c:"STK-E87F",v:"",s:"Aguard. Deploy PRD",r:"Lourene",mr:"https://gitlab.luizalabs.com/luizalabs/fintech/sesamo/-/merge_requests/3123",a:"27/05 - Q.A em andamento\n26/05 - Deploy em STG\n15/05 - Inicio do desenvolvimento"},
 {id:11,g:"Demais Atividades",t:"2.25 - Incluir melhoria na validacao de CPF",c:"IMP-5218",v:"v0.10.2/v0.10.3",s:"Finalizado",r:"Islan",mr:"https://gitlab.luizalabs.com/luizalabs/fintech/sesamo/-/merge_requests/3181",a:"28/05 - Deploy em PRD\n26/05 - Deploy em STG\n26/05 - Inicio do desenvolvimento"},
 {id:12,g:"Migrar Notify Kafka-Bull",t:"13.3 - Adaptar conexao Redis para modo Cluster",c:"STK-9FD0",v:"",s:"Aguard. Deploy PRD",r:"Diguinho",mr:"https://gitlab.luizalabs.com/luizalabs/fintech/sesamo/-/merge_requests/2989",a:"29/05 - Aguardando deploy PRD\n26/05 - Deploy em STG\n06/03 - Inicio do desenvolvimento"},
 {id:13,g:"Migrar Notify Kafka-Bull",t:"13.4 - Autenticacao no endpoint OPS",c:"STK-F121",v:"",s:"Aguard. Deploy PRD",r:"Diguinho",mr:"",a:"29/05 - Aguardando deploy PRD\n26/05 - Deploy em STG\n20/02 - Inicio do desenvolvimento"},
 {id:14,g:"Migrar Notify Kafka-Bull",t:"13.5 - sesamo-api - dual publish Redis/Kafka",c:"STK-BA16",v:"",s:"Paralisado",r:"Matheus",mr:"",a:"30/04 - MR validado\n17/04 - Inicio do desenvolvimento"},
 {id:15,g:"Migrar Notify Kafka-Bull",t:"13.6 - Configuracao de retry por canal",c:"STK-97D0",v:"",s:"Paralisado",r:"Matheus",mr:"",a:"05/05 - MR validado\n04/05 - Inicio do desenvolvimento"},
 {id:16,g:"Migrar Notify Kafka-Bull",t:"13.7 - Rollout do jaiminho canal-por-canal",c:"STK-DE23",v:"",s:"Paralisado",r:"Matheus",mr:"",a:"13/05 - MR validado\n29/04 - Inicio do desenvolvimento"},
 {id:17,g:"Migrar Notify Kafka-Bull",t:"13.8 - Melhorar cobertura de codigo",c:"STK-B3F6",v:"",s:"Em andamento",r:"Matheus",mr:"",a:"18/05 - Liberado MR\n05/05 - Inicio do desenvolvimento"},
 {id:18,g:"Migrar Notify Kafka-Bull",t:"13.9 - Q.A - Planejamento de cenarios",c:"",v:"",s:"Em andamento",r:"Matheus",mr:"",a:"18/05 - Inicio do desenvolvimento"},
 {id:19,g:"Migrar Notify Kafka-Bull",t:"13.10 - Q.A - Execucao",c:"",v:"",s:"Nao Iniciado",r:"",mr:"",a:""},
 {id:20,g:"Migrar Notify Kafka-Bull",t:"13.11 - Analise e Refatoracao do Core Notifier",c:"STK-616E",v:"",s:"Nao Iniciado",r:"",mr:"",a:""},
 {id:21,g:"Migrar Notify Kafka-Bull",t:"13.12 - Adicionar delay por canal",c:"STK-56BA",v:"",s:"Nao Iniciado",r:"",mr:"",a:""},
 {id:22,g:"Controle de BINs - Fase II",t:"14.2 - [BIN Fase II] Fundacao e Orquestracao",c:"STK-55DF",v:"",s:"Em andamento",r:"Aleson",mr:"",a:"17/04 - Inicio do desenvolvimento"},
 {id:23,g:"Controle de BINs - Fase II",t:"14.3 - [BIN Fase II] API + Testes",c:"STK-CD0A",v:"",s:"Em andamento",r:"Camila",mr:"",a:""},
 {id:24,g:"Evolucao Sesamo - Jedi Netshoes",t:"15.1 - Alteracao payload Pix + Cartao",c:"STK-77B0",v:"",s:"Em andamento",r:"Aleson",mr:"",a:"26/05 - Seguindo\n21/05 - Inicio do desenvolvimento"},
 {id:25,g:"Evolucao Sesamo - Jedi Netshoes",t:"15.3 - Refinar politica de retentativa Antifraude",c:"STK-BDD7",v:"",s:"Aguard. Deploy PRD",r:"Aleson",mr:"",a:"27/05 - Q.A em andamento\n25/05 - Deploy em STG\n18/05 - Inicio do desenvolvimento"},
 {id:26,g:"PIX + Voucher - Konduto",t:"16.1 - Habilitar fluxo PIX + Voucher via Konduto",c:"STK-3FE4",v:"",s:"Aguard. Deploy PRD",r:"Lourene",mr:"",a:"29/05 - Aguardando deploy PRD\n26/05 - Deploy em STG\n07/05 - Inicio do desenvolvimento"},
 {id:27,g:"PIX + Voucher - Konduto",t:"16.2 - Refinar politica de retentativa",c:"STK-BDD7",v:"",s:"Nao Iniciado",r:"",mr:"",a:""},
 {id:28,g:"Monopoly OPS",t:"4.5 - [Monopoly] Alta - Infinite loop",c:"OPS-50A6",v:"",s:"Aguard. Deploy PRD",r:"Lourene",mr:"",a:"29/05 - Validado em STG\n26/05 - Deploy em STG\n07/05 - Inicio do desenvolvimento"},
 {id:29,g:"Monopoly OPS",t:"4.9 - [Monopoly] Alta - Timing Attack",c:"OPS-F15A",v:"",s:"Nao Iniciado",r:"",mr:"",a:""},
 {id:30,g:"Monopoly OPS",t:"4.11 - [Monopoly] Alta - Allocation of Resources",c:"OPS-F8C7",v:"",s:"Nao Iniciado",r:"",mr:"",a:""},
 {id:31,g:"Monopoly OPS",t:"4.12 - [Monopoly] Alta - Allocation of Resources",c:"OPS-47F1",v:"",s:"Nao Iniciado",r:"",mr:"",a:""},
 {id:32,g:"Monopoly OPS",t:"4.13 - [Monopoly] Alta - Race Condition",c:"OPS-6133",v:"",s:"Nao Iniciado",r:"",mr:"",a:""},
 {id:33,g:"Monopoly OPS",t:"4.14 - [Monopoly] Alta - Infinite loop",c:"OPS-4C49",v:"",s:"Nao Iniciado",r:"",mr:"",a:""},
 {id:34,g:"Destrava 3P - IN",t:"9.2 - Banco de dados",c:"STK-755E",v:"",s:"Entregue",r:"Islan",mr:"",a:"15/04 - MR validado\n06/02 - Inicio do desenvolvimento"},
 {id:35,g:"Destrava 3P - IN",t:"9.3 - Regras de Negocio e Validacoes",c:"STK-4760",v:"",s:"Entregue",r:"Islan",mr:"",a:"15/04 - MR validado\n06/02 - Inicio do desenvolvimento"},
 {id:36,g:"Destrava 3P - IN",t:"9.5 - Logica de negocio e Ajustes",c:"STK-B8AC",v:"",s:"Entregue",r:"Islan",mr:"",a:"15/04 - MR validado\n12/02 - Inicio do desenvolvimento"},
 {id:37,g:"Destrava 3P - IN",t:"9.6 - API REST e documentacao Swagger",c:"STK-4E90",v:"",s:"Entregue",r:"Islan",mr:"",a:"15/04 - MR validado\n13/02 - Inicio do desenvolvimento"},
 {id:38,g:"Destrava 3P - IN",t:"9.8 - Q.A - Destrava IN",c:"STK-C714",v:"",s:"Em andamento",r:"Aleson",mr:"",a:""},
 {id:39,g:"Destrava 3P - IN",t:"9.9 - Aplicar comportamento para endpoints v2",c:"STK-B301",v:"",s:"Entregue",r:"Islan",mr:"",a:"15/04 - MR validado\n25/02 - Inicio do desenvolvimento"},
 {id:40,g:"Destrava 3P - IN",t:"9.13 - Criacao endpoint de consulta de pedidos",c:"STK-4555",v:"",s:"Entregue",r:"Islan",mr:"",a:"15/04 - MR validado\n13/04 - Inicio do desenvolvimento"},
 {id:41,g:"Controle de BINs - Fase I",t:"6.11 - Carga na tabela de PRD",c:"STK-63CE",v:"",s:"Aguard. Deploy PRD",r:"",mr:"",a:""},
 {id:42,g:"Sanitizacao Swagger",t:"10.17 - Adicionar step de validacao na pipeline",c:"STK-E772",v:"",s:"Aguard. Deploy PRD",r:"Diguinho",mr:"",a:"29/05 - Aguardando deploy PRD\n20/02 - Inicio do desenvolvimento"},
 {id:43,g:"Sanitizacao Swagger",t:"10.20 - Equalizacao Swagger Order + validacao OpenAPI",c:"STK-7C3F",v:"",s:"Aguard. Deploy PRD",r:"Aleson",mr:"",a:"29/05 - Aguardando deploy PRD\n13/05 - Inicio do desenvolvimento"},
 {id:44,g:"Sanitizacao Swagger",t:"10.22 - Mapeamento, Migracao e Ajustes pendentes",c:"STK-9FDF",v:"",s:"Em andamento",r:"Aleson",mr:"",a:"26/05 - Seguindo\n21/05 - Inicio do desenvolvimento"},
 {id:45,g:"Wallet - Fase 4",t:"17.0 - [Reanalise de Risco] Discovery Produto",c:"",v:"",s:"Em andamento",r:"",mr:"",a:""},
 {id:46,g:"Wallet - Fase 4",t:"17.0 - [Reanalise de Risco] Refinamento Tecnico",c:"",v:"",s:"Bloqueado",r:"",mr:"",a:""},
 {id:47,g:"Wallet - Fase 4",t:"18.0 - [Callback Canal JEDI] Discovery Produto",c:"",v:"",s:"Em andamento",r:"",mr:"",a:""},
 {id:48,g:"Wallet - Fase 4",t:"18.0 - [Callback Canal JEDI] Refinamento Tecnico",c:"",v:"",s:"Bloqueado",r:"",mr:"",a:""},
 {id:49,g:"Smart Routing",t:"22.0 - Discovery Produto",c:"",v:"",s:"Nao Iniciado",r:"",mr:"",a:""},
 {id:50,g:"Smart Routing",t:"22.1 - Refinamento Tecnico",c:"",v:"",s:"Nao Iniciado",r:"",mr:"",a:""},
];

